### ISSUE TITLE
Handle input source map

### ISSUE THREAD

**Issue by OliverJAsh** [walbo/grunt-px-to-rem#10]
If a file has a source map annotation, Pixrem removes it. Pixrem should handle the input source map.

**Comment by walbo** [comment]
I'll take a look at it later today.

**Comment by walbo** [comment]
Have updated the files here on github. Going to test it a little more before I push it to the npm register.

Appreciate if you can test the github version, and give me a feedback.

Will probably push it to npm later tonight or tomorrow.

**Comment by walbo** [comment]
Look like the source map isn't matching after px_to_rem.

**Comment by walbo** [comment]
Introduced `map` option.

See: https://github.com/walbo/grunt-px-to-rem#optionsmap

**Comment by walbo** [comment]
0.4.0 handles source maps.

Please update your map option and update to 0.4.0

**Comment by sndrs** [comment]
magic, thank you!
