### ISSUE TITLE
Unclosed quote error within comments

### ISSUE THREAD

**Issue by krisbulman** [walbo/grunt-px-to-rem#11]
Verbose output:

> Running "px_to_rem:dist" (px_to_rem) task
> Options: base=16, fallback=false, fallback_existing_rem=false, max_decimals=20, ignore=[], map=false
> Reading sass/styles.scss...OK
> Warning: styles.scss:1:239: Unclosed quote Use --force to continue.

This error is misleading, i originally thought it was coming from normalize, but just realized it's pointing to styles.scss, which is just imports: 

``` SCSS
// Don't add external dependencies to libraries, such as compass, here.
// Use Gruntfile.js

@import 'core/variables';
@import 'vendor';
@import 'core/functions';
@import 'core/mixins';
@import 'base';
@import 'layout';
@import 'component';
```

**Comment by walbo** [comment]
Ok. Great.. Try running px-to-rem on the compiled css files.

**Comment by krisbulman** [comment]
HAH! rookie mistake. it was parsing Sass comments.

**Comment by krisbulman** [comment]
works like a charm, thanks for spotting that. this grunt plugin made my day, cheers!
